# Generated by Django 6.0.4 on 2026-04-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='العنوان')),
                ('category', models.CharField(choices=[('cement', 'إسمنت وخرسانة'), ('steel', 'حديد وتسليح'), ('wood', 'أخشاب'), ('paint', 'دهانات'), ('ceramic', 'سيراميك وبورسلين'), ('plumbing', 'سباكة'), ('electrical', 'كهرباء'), ('tools', 'أدوات'), ('general', 'عام')], default='general', max_length=20, verbose_name='تصنيف المورد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
                'ordering': ['name'],
            },
        ),
    ]
