# Generated by Django 6.0.4 on 2026-08-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('detergents', 'منظفات سائلة'), ('powders', 'مساحيق غسيل'), ('disinfectants', 'مطهرات ومعقمات'), ('papers', 'ورقيات ومناديل'), ('tools', 'أدوات ومعدات تنظيف'), ('chemicals', 'مواد كيميائية خام'), ('general', 'عام')], default='general', max_length=20, verbose_name='تصنيف المورد'),
        ),
    ]
