# Generated by Django 6.0.4 on 2026-08-09 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('invoice_date', models.DateField(verbose_name='تاريخ الفاتورة')),
                ('supplier_invoice_date', models.DateField(blank=True, null=True, verbose_name='تاريخ فاتورة المورد')),
                ('supplier_bill_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم فاتورة المورد')),
                ('statement', models.CharField(blank=True, max_length=500, null=True, verbose_name='البيان')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم المرجعي')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='suppliers.supplier', verbose_name='المورد')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='warehouses.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'فاتورة شراء',
                'verbose_name_plural': 'فواتير الشراء',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر البيع')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التخفيض')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_details', to='products.product', verbose_name='المنتج')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='purchases.purchaseinvoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'تفاصيل الفاتورة',
                'verbose_name_plural': 'تفاصيل الفواتير',
            },
        ),
    ]
