# Generated by Django 6.0.4 on 2026-04-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='العنوان')),
                ('customer_type', models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة مقاولات'), ('store', 'متجر')], default='individual', max_length=20, verbose_name='نوع العميل')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المشتريات')),
                ('total_invoices', models.IntegerField(default=0, verbose_name='عدد الفواتير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['name'],
            },
        ),
    ]
