# Generated by Django 6.0.4 on 2026-04-09 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='الباركود')),
                ('unit', models.CharField(choices=[('bag', 'كيس'), ('piece', 'قطعة'), ('meter', 'متر'), ('square_meter', 'متر مربع'), ('ton', 'طن'), ('kg', 'كيلوجرام'), ('barrel', 'برميل'), ('gallon', 'جالون'), ('box', 'كرتونة'), ('roll', 'لفة'), ('sheet', 'لوح'), ('liter', 'لتر')], default='piece', max_length=20, verbose_name='وحدة القياس')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الشراء')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر البيع')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية الحالية')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للتنبيه')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الوزن (كجم)')),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الطول (متر)')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون')),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True, verbose_name='الشركة المصنعة')),
                ('has_expiry', models.BooleanField(default=False, verbose_name='له تاريخ انتهاء')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='التصنيف')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='warehouses.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['category', 'name'],
            },
        ),
    ]
