# Generated by Django 6.0.4 on 2026-08-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرائحة / اللون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_expiry',
            field=models.BooleanField(default=True, verbose_name='له تاريخ انتهاء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الأبعاد (متر)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'قطعة'), ('bottle', 'قنينة'), ('gallon', 'جالون'), ('liter', 'لتر'), ('ml', 'مليلتر'), ('box', 'كرتونة'), ('packet', 'باكو'), ('dozen', 'دزينة'), ('drum', 'برميل')], default='piece', max_length=20, verbose_name='وحدة القياس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الوزن / الحجم (كجم/لتر)'),
        ),
    ]
